<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DB::table('countries')->truncate();
        $countries = [
            ['name' => 'Afghanistan', 'name_lan'=>'አፍጋኒስታን','description'=> 'AF','description_lan'=>''],
            ['name' => 'Åland Islands', 'name_lan'=>'የአላንድ ደሴቶች','description'=> 'AX','description_lan'=>''],
            ['name' => 'Albania', 'name_lan'=>'አልባኒያ','description'=> 'AL','description_lan'=>''],
            ['name' => 'Algeria', 'name_lan'=>'አልጄሪያ','description'=> 'DZ','description_lan'=>''],
            ['name' => 'American Samoa', 'name_lan'=>'አሜሪካዊ ሳሞአ','description'=> 'AS','description_lan'=>''],
            ['name' => 'Andorra', 'name_lan'=>'አንዶራ','description'=> 'AD','description_lan'=>''],
            ['name' => 'Angola', 'name_lan'=>'አንጎላ','description'=> 'AO','description_lan'=>''],
            ['name' => 'Anguilla', 'name_lan'=>'አንጉላ','description'=> 'AI','description_lan'=>''],
            ['name' => 'Antarctica', 'name_lan'=>'አንታርክቲካ','description'=> 'AQ','description_lan'=>''],
            ['name' => 'Antigua and Barbuda', 'name_lan'=>'አንቲጉአ እና ባርቡዳ','description'=> 'AG','description_lan'=>''],
            ['name' => 'Argentina', 'name_lan'=>'አርጀንቲና','description'=> 'AR','description_lan'=>''],
            ['name' => 'Armenia', 'name_lan'=>'አርሜኒያ','description'=> 'AM','description_lan'=>''],
            ['name' => 'Aruba', 'name_lan'=>'አሩባ','description'=> 'AW','description_lan'=>''],
            ['name' => 'Australia', 'name_lan'=>'አውስትራሊያ','description'=> 'AU','description_lan'=>''],
            ['name' => 'Austria', 'name_lan'=>'ኦስትራ','description'=> 'AT','description_lan'=>''],
            ['name' => 'Azerbaijan', 'name_lan'=>'አዘርባጃን','description'=> 'AZ','description_lan'=>''],
            ['name' => 'Bahamas', 'name_lan'=>'ባሐማስ','description'=> 'BS','description_lan'=>''],
            ['name' => 'Bahrain', 'name_lan'=>'ባሃሬን','description'=> 'BH','description_lan'=>''],
            ['name' => 'Bangladesh', 'name_lan'=>'ባንግላድሽ','description'=> 'BD','description_lan'=>''],
            ['name' => 'Barbados', 'name_lan'=>'ባርባዶስ','description'=> 'BB','description_lan'=>''],
            ['name' => 'Belarus', 'name_lan'=>'ቤላሩስ','description'=> 'BY','description_lan'=>''],
            ['name' => 'Belgium', 'name_lan'=>'ቤልጄም','description'=> 'BE','description_lan'=>''],
            ['name' => 'Belize', 'name_lan'=>'ቤሊዜ','description'=> 'BZ','description_lan'=>''],
            ['name' => 'Benin', 'name_lan'=>'ቤኒኒ','description'=> 'BJ','description_lan'=>''],
            ['name' => 'Bermuda', 'name_lan'=>'ቤርሙዳ','description'=> 'BM','description_lan'=>''],
            ['name' => 'Bhutan', 'name_lan'=>'በሓቱን','description'=> 'BT','description_lan'=>''],
            ['name' => 'Bolivia, Plurinational State of', 'name_lan'=>'ቦሊቪያ','description'=> 'BO','description_lan'=>''],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'name_lan'=>'ቦናይየር','description'=> 'BQ','description_lan'=>''],
            ['name' => 'Bosnia and Herzegovina', 'name_lan'=>'ቦስኒያ እና ሔርዞጎቪያ','description'=> 'BA','description_lan'=>''],
            ['name' => 'Botswana', 'name_lan'=>'ቦትስዋና','description'=> 'BW','description_lan'=>''],
            ['name' => 'Bouvet Island', 'name_lan'=>'ቡቬት ደሴት','description'=> 'BV','description_lan'=>''],
            ['name' => 'Brazil', 'name_lan'=>'ብራዚል','description'=> 'BR','description_lan'=>''],
            ['name' => 'British Indian Ocean Territory', 'name_lan'=>'የእንግሊዝ የሕንድ ውቅያኖስ ግዛት','description'=> 'IO','description_lan'=>''],
            ['name' => 'Brunei Darussalam', 'name_lan'=>'ብሩኒ ዳሩሰላም','description'=> 'BN','description_lan'=>''],
            ['name' => 'Bulgaria', 'name_lan'=>'ቡልጋሪያ','description'=> 'BG','description_lan'=>''],
            ['name' => 'Burkina Faso', 'name_lan'=>' ቡርክናፋሶ','description'=> 'BF','description_lan'=>''],
            ['name' => 'Burundi', 'name_lan'=>'ቡሩንዲ','description'=> 'BI','description_lan'=>''],
            ['name' => 'Cambodia', 'name_lan'=>'ካምቦዲያ','description'=> 'KH','description_lan'=>''],
            ['name' => 'Cameroon', 'name_lan'=>'ካሜሩን','description'=> 'CM','description_lan'=>''],
            ['name' => 'Canada', 'name_lan'=>'ካናዳ','description'=> 'CA','description_lan'=>''],
            ['name' => 'Cape Verde', 'name_lan'=>'ኬፕ ቬሪዴ','description'=> 'CV','description_lan'=>''],
            ['name' => 'Cayman Islands', 'name_lan'=>'ኬይማን አይስላንድ','description'=> 'KY','description_lan'=>''],
            ['name' => 'Central African Republic', 'name_lan'=>'','description'=> 'CF','description_lan'=>''],
            ['name' => 'Chad', 'name_lan'=>'ሴንትራል አፍሪካ ሪፑቢሊክ','description'=> 'TD','description_lan'=>''],
            ['name' => 'Chile', 'name_lan'=>' ቻድ','description'=> 'CL','description_lan'=>''],
            ['name' => 'China', 'name_lan'=>'ቺሊ','description'=> 'CN','description_lan'=>''],
            ['name' => 'Christmas Island', 'name_lan'=>' ቻይና','description'=> 'CX','description_lan'=>''],
            ['name' => 'Cocos (Keeling) Islands', 'name_lan'=>' የገና ደሴት','description'=> 'CC','description_lan'=>''],
            ['name' => 'Colombia', 'name_lan'=>'ኮኮስ (ኬሊንግ) ደሴቶች','description'=> 'CO','description_lan'=>''],
            ['name' => 'Comoros', 'name_lan'=>'ኮሎምቢያ','description'=> 'KM','description_lan'=>''],
            ['name' => 'Congo', 'name_lan'=>'ኮሞሮስ','description'=> 'CG','description_lan'=>''],
            ['name' => 'Congo, the Democratic Republic of the', 'name_lan'=>'ኮንጎ','description'=> 'CD','description_lan'=>''],
            ['name' => 'Cook Islands', 'name_lan'=>'ኩክ አይስላንድስ','description'=> 'CK','description_lan'=>''],
            ['name' => 'Costa Rica', 'name_lan'=>'ኮስታሪካ','description'=> 'CR','description_lan'=>''],
            ['name' => 'Côte d\'Ivoire', 'name_lan'=>'ኮትዲቫር','description'=> 'CI','description_lan'=>''],
            ['name' => 'Croatia', 'name_lan'=>'ክሮሽያ','description'=> 'HR','description_lan'=>''],
            ['name' => 'Cuba', 'name_lan'=>'ኩባ','description'=> 'CU','description_lan'=>''],
            ['name' => 'Curaçao', 'name_lan'=>'ኩራኦ','description'=> 'CW','description_lan'=>''],
            ['name' => 'Cyprus', 'name_lan'=>'ቆጵሮስ','description'=> 'CY','description_lan'=>''],
            ['name' => 'Czech Republic', 'name_lan'=>'ቼክ ሪፐብሊክ','description'=> 'CZ','description_lan'=>''],
            ['name' => 'Denmark', 'name_lan'=>'ዴንማሪክ','description'=> 'DK','description_lan'=>''],
            ['name' => 'Djibouti', 'name_lan'=>'ጅቡቲ','description'=> 'DJ','description_lan'=>''],
            ['name' => 'Dominica', 'name_lan'=>'ዶሚኒካ','description'=> 'DM','description_lan'=>''],
            ['name' => 'Dominican Republic', 'name_lan'=>'ዶሚኒካን ሪፑብሊክ','description'=> 'DO','description_lan'=>''],
            ['name' => 'Ecuador', 'name_lan'=>'ኢኳዶር','description'=> 'EC','description_lan'=>''],
            ['name' => 'Egypt', 'name_lan'=>'ግብጽ','description'=> 'EG','description_lan'=>''],
            ['name' => 'El Salvador', 'name_lan'=>'ኤልሳልቫዶር','description'=> 'SV','description_lan'=>''],
            ['name' => 'Equatorial Guinea', 'name_lan'=>'ኢኳቶሪያል ጊኒ','description'=> 'GQ','description_lan'=>''],
            ['name' => 'Eritrea', 'name_lan'=>'ኤርትሪያ','description'=> 'ER','description_lan'=>''],
            ['name' => 'Estonia', 'name_lan'=>'ኢስቶኒያ','description'=> 'EE','description_lan'=>''],
            ['name' => 'Ethiopia', 'name_lan'=>'ኢትዮጵያ','description'=> 'ET','description_lan'=>''],
            ['name' => 'Falkland Islands (Malvinas)', 'name_lan'=>'የፎክላንድ ደሴቶች (ማልቪናስ)','description'=> 'FK','description_lan'=>''],
            ['name' => 'Faroe Islands', 'name_lan'=>'ፋሮ ደሴቶች','description'=> 'FO','description_lan'=>''],
            ['name' => 'Fiji', 'name_lan'=>'ፊጂ','description'=> 'FJ','description_lan'=>''],
            ['name' => 'Finland', 'name_lan'=>'ፊኒላንድ','description'=> 'FI','description_lan'=>''],
            ['name' => 'France', 'name_lan'=>'ፈረንሳይ','description'=> 'FR','description_lan'=>''],
            ['name' => 'French Guiana', 'name_lan'=>'የፈረንሳይ ጉያና','description'=> 'GF','description_lan'=>''],
            ['name' => 'French Polynesia', 'name_lan'=>'የፈረንሳይ ፖሊኔዥያ','description'=> 'PF','description_lan'=>''],
            ['name' => 'French Southern Territories', 'name_lan'=>'የፈረንሳይ ደቡባዊ ግዛቶች','description'=> 'TF','description_lan'=>''],
            ['name' => 'Gabon', 'name_lan'=>'ጋቦን','description'=> 'GA','description_lan'=>''],
            ['name' => 'Gambia', 'name_lan'=>'ጋምቢያ','description'=> 'GM','description_lan'=>''],
            ['name' => 'Georgia', 'name_lan'=>'ጆርጂያ','description'=> 'GE','description_lan'=>''],
            ['name' => 'Germany', 'name_lan'=>'ጀርመን','description'=> 'DE','description_lan'=>''],
            ['name' => 'Ghana', 'name_lan'=>'ጋና','description'=> 'GH','description_lan'=>''],
            ['name' => 'Gibraltar', 'name_lan'=>'ጊብራልታር','description'=> 'GI','description_lan'=>''],
            ['name' => 'Greece', 'name_lan'=>'ግሪክ','description'=> 'GR','description_lan'=>''],
            ['name' => 'Greenland', 'name_lan'=>'ግሪንላንድ','description'=> 'GL','description_lan'=>''],
            ['name' => 'Grenada', 'name_lan'=>'ግሪንዳዳ','description'=> 'GD','description_lan'=>''],
            ['name' => 'Guadeloupe', 'name_lan'=>'ጓደሎፕ','description'=> 'GP','description_lan'=>''],
            ['name' => 'Guam', 'name_lan'=>'ጉአሜ','description'=> 'GU','description_lan'=>''],
            ['name' => 'Guatemala', 'name_lan'=>'ጓቴማላ','description'=> 'GT','description_lan'=>''],
            ['name' => 'Guernsey', 'name_lan'=>'ገርንሴይ','description'=> 'GG','description_lan'=>''],
            ['name' => 'Guinea', 'name_lan'=>'ጊኒ','description'=> 'GN','description_lan'=>''],
            ['name' => 'Guinea-Bissau', 'name_lan'=>'ጊኒ ቢሳው','description'=> 'GW','description_lan'=>''],
            ['name' => 'Guyana', 'name_lan'=>'ጉያና','description'=> 'GY','description_lan'=>''],
            ['name' => 'Haiti', 'name_lan'=>'ሓይቲ','description'=> 'HT','description_lan'=>''],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'name_lan'=>'ሄርድ ደሴት እና ማክዶናልድ ማክዶናልድ ደሴቶች','description'=> 'HM','description_lan'=>''],
            ['name' => 'Holy See (Vatican City State)', 'name_lan'=>'ቅድስት መንበር (የቫቲካን ከተማ ግዛት)','description'=> 'VA','description_lan'=>''],
            ['name' => 'Honduras', 'name_lan'=>'ሆንዱራስ','description'=> 'HN','description_lan'=>''],
            ['name' => 'Hong Kong', 'name_lan'=>'ሆንግ ኮንግ','description'=> 'HK','description_lan'=>''],
            ['name' => 'Hungary', 'name_lan'=>'ሃንጋሪ','description'=> 'HU','description_lan'=>''],
            ['name' => 'Iceland', 'name_lan'=>'አይስላንድ','description'=> 'IS','description_lan'=>''],
            ['name' => 'India', 'name_lan'=>'ሕንድ','description'=> 'IN','description_lan'=>''],
            ['name' => 'Indonesia', 'name_lan'=>'ኢንዶኔዥያ','description'=> 'ID','description_lan'=>''],
            ['name' => 'Iran, Islamic Republic of', 'name_lan'=>'ኢራን','description'=> 'IR','description_lan'=>''],
            ['name' => 'Iraq', 'name_lan'=>'ኢራቅ','description'=> 'IQ','description_lan'=>''],
            ['name' => 'Ireland', 'name_lan'=>'አይርላድ','description'=> 'IE','description_lan'=>''],
            ['name' => 'Isle of Man', 'name_lan'=>'የሰው ደሴት','description'=> 'IM','description_lan'=>''],
            ['name' => 'Israel', 'name_lan'=>'እስራኤል','description'=> 'IL','description_lan'=>''],
            ['name' => 'Italy', 'name_lan'=>'ጣሊያን','description'=> 'IT','description_lan'=>''],
            ['name' => 'Jamaica', 'name_lan'=>'ጃማይካ','description'=> 'JM','description_lan'=>''],
            ['name' => 'Japan', 'name_lan'=>'ጃፓን','description'=> 'JP','description_lan'=>''],
            ['name' => 'Jersey', 'name_lan'=>'ጀርሲ','description'=> 'JE','description_lan'=>''],
            ['name' => 'Jordan', 'name_lan'=>'ዮርዳኖስ','description'=> 'JO','description_lan'=>''],
            ['name' => 'Kazakhstan', 'name_lan'=>'ካዛክስታን','description'=> 'KZ','description_lan'=>''],
            ['name' => 'Kenya', 'name_lan'=>'ኬንያ','description'=> 'KE','description_lan'=>''],
            ['name' => 'Kiribati', 'name_lan'=>'ኪሪባቲ','description'=> 'KI','description_lan'=>''],
            ['name' => 'Korea, Democratic People\'s Republic of', 'name_lan'=>'ኮሪያ','description'=> 'KP','description_lan'=>''],
            ['name' => 'Korea, Republic of', 'name_lan'=>'ኮሪያ','description'=> 'KR','description_lan'=>''],
            ['name' => 'Kuwait', 'name_lan'=>'ኵዌት','description'=> 'KW','description_lan'=>''],
            ['name' => 'Kyrgyzstan', 'name_lan'=>'ክይርጋዝስታን','description'=> 'KG','description_lan'=>''],
            ['name' => 'Lao People\'s Democratic Republic', 'name_lan'=>'ላኦ ሕዝባዊ ዴሞክራሲያዊ ሪፐብሊክ','description'=> 'LA','description_lan'=>''],
            ['name' => 'Latvia', 'name_lan'=>'ላቲቪያ','description'=> 'LV','description_lan'=>''],
            ['name' => 'Lebanon', 'name_lan'=>'ሊባኖስ','description'=> 'LB','description_lan'=>''],
            ['name' => 'Lesotho', 'name_lan'=>'ሌስቶ','description'=> 'LS','description_lan'=>''],
            ['name' => 'Liberia', 'name_lan'=>'ላይቤሪያ','description'=> 'LR','description_lan'=>''],
            ['name' => 'Libya', 'name_lan'=>'ሊቢያ','description'=> 'LY','description_lan'=>''],
            ['name' => 'Liechtenstein', 'name_lan'=>'ለይችቴንስቴይን','description'=> 'LI','description_lan'=>''],
            ['name' => 'Lithuania', 'name_lan'=>'ሊቱአኒያ','description'=> 'LT','description_lan'=>''],
            ['name' => 'Luxembourg', 'name_lan'=>'ሉዘምቤርግ','description'=> 'LU','description_lan'=>''],
            ['name' => 'Macao', 'name_lan'=>'ማካው','description'=> 'MO','description_lan'=>''],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'name_lan'=>'መቄዶኒያ','description'=> 'MK','description_lan'=>''],
            ['name' => 'Madagascar', 'name_lan'=>'ማዳጋስካር','description'=> 'MG','description_lan'=>''],
            ['name' => 'Malawi', 'name_lan'=>'ማላዊ','description'=> 'MW','description_lan'=>''],
            ['name' => 'Malaysia', 'name_lan'=>'ማሌዥያ','description'=> 'MY','description_lan'=>''],
            ['name' => 'Maldives', 'name_lan'=>'ማልዲቬስ','description'=> 'MV','description_lan'=>''],
            ['name' => 'Mali', 'name_lan'=>'ማሊ','description'=> 'ML','description_lan'=>''],
            ['name' => 'Malta', 'name_lan'=>'ማልታ','description'=> 'MT','description_lan'=>''],
            ['name' => 'Marshall Islands', 'name_lan'=>'ማርሻል አይስላንድ','description'=> 'MH','description_lan'=>''],
            ['name' => 'Martinique', 'name_lan'=>'ማርቲኒክ','description'=> 'MQ','description_lan'=>''],
            ['name' => 'Mauritania', 'name_lan'=>'ሞሪታኒያ','description'=> 'MR','description_lan'=>''],
            ['name' => 'Mauritius', 'name_lan'=>'ሞሪሼስ','description'=> 'MU','description_lan'=>''],
            ['name' => 'Mayotte', 'name_lan'=>'ማዮት','description'=> 'YT','description_lan'=>''],
            ['name' => 'Mexico', 'name_lan'=>'ሜክስኮ','description'=> 'MX','description_lan'=>''],
            ['name' => 'Micronesia, Federated States of', 'name_lan'=>'ሚክሮኔዥያ','description'=> 'FM','description_lan'=>''],
            ['name' => 'Moldova, Republic of', 'name_lan'=>'ሞልዶቫ','description'=> 'MD','description_lan'=>''],
            ['name' => 'Monaco', 'name_lan'=>'ሞናኮ','description'=> 'MC','description_lan'=>''],
            ['name' => 'Mongolia', 'name_lan'=>'ሞንጎሊያ','description'=> 'MN','description_lan'=>''],
            ['name' => 'Montenegro', 'name_lan'=>'ሞንቴኔግሮ','description'=> 'ME','description_lan'=>''],
            ['name' => 'Montserrat', 'name_lan'=>'ሞንትሴራት','description'=> 'MS','description_lan'=>''],
            ['name' => 'Morocco', 'name_lan'=>'ሞሮኮ','description'=> 'MA','description_lan'=>''],
            ['name' => 'Mozambique', 'name_lan'=>'ሞዛምቢክ','description'=> 'MZ','description_lan'=>''],
            ['name' => 'Myanmar', 'name_lan'=>'ማይንማር','description'=> 'MM','description_lan'=>''],
            ['name' => 'Namibia', 'name_lan'=>'ናምቢያ','description'=> 'NA','description_lan'=>''],
            ['name' => 'Nauru', 'name_lan'=>'ናኡሩ','description'=> 'NR','description_lan'=>''],
            ['name' => 'Nepal', 'name_lan'=>'ኔፓል','description'=> 'NP','description_lan'=>''],
            ['name' => 'Netherlands', 'name_lan'=>'ኔዜሪላንድ','description'=> 'NL','description_lan'=>''],
            ['name' => 'New Caledonia', 'name_lan'=>'ኒው ካሌዶኒያ','description'=> 'NC','description_lan'=>''],
            ['name' => 'New Zealand', 'name_lan'=>'ኒውዚላንድ','description'=> 'NZ','description_lan'=>''],
            ['name' => 'Nicaragua', 'name_lan'=>'ኒካራጉአ','description'=> 'NI','description_lan'=>''],
            ['name' => 'Niger', 'name_lan'=>'ኒጀር','description'=> 'NE','description_lan'=>''],
            ['name' => 'Nigeria', 'name_lan'=>'ናይጄሪያ','description'=> 'NG','description_lan'=>''],
            ['name' => 'Niue', 'name_lan'=>'ኒይኡ','description'=> 'NU','description_lan'=>''],
            ['name' => 'Norfolk Island', 'name_lan'=>'ኖርፎልክ አይስላንድስ','description'=> 'NF','description_lan'=>''],
            ['name' => 'Northern Mariana Islands', 'name_lan'=>'የሰሜናዊ ማሪያና አይስላንድስ','description'=> 'MP','description_lan'=>''],
            ['name' => 'Norway', 'name_lan'=>'ኖርዌይ','description'=> 'NO','description_lan'=>''],
            ['name' => 'Oman', 'name_lan'=>'ኦማን','description'=> 'OM','description_lan'=>''],
            ['name' => 'Pakistan', 'name_lan'=>'ፓኪስታን','description'=> 'PK','description_lan'=>''],
            ['name' => 'Palau', 'name_lan'=>'ፓላኡ','description'=> 'PW','description_lan'=>''],
            ['name' => 'Palestine, State of', 'name_lan'=>'ፍልስጥኤም','description'=> 'PS','description_lan'=>''],
            ['name' => 'Panama', 'name_lan'=>'ፓናማ','description'=> 'PA','description_lan'=>''],
            ['name' => 'Papua New Guinea', 'name_lan'=>'ፓፓያ ኒው ጊኒ','description'=> 'PG','description_lan'=>''],
            ['name' => 'Paraguay', 'name_lan'=>'ፓራጓይ','description'=> 'PY','description_lan'=>''],
            ['name' => 'Peru', 'name_lan'=>'ፔሩ','description'=> 'PE','description_lan'=>''],
            ['name' => 'Philippines', 'name_lan'=>'ፊሊፕንሲ','description'=> 'PH','description_lan'=>''],
            ['name' => 'Pitcairn', 'name_lan'=>'ፒትካርን','description'=> 'PN','description_lan'=>''],
            ['name' => 'Poland', 'name_lan'=>'ፖላንድ','description'=> 'PL','description_lan'=>''],
            ['name' => 'Portugal', 'name_lan'=>'ፖርቹጋል','description'=> 'PT','description_lan'=>''],
            ['name' => 'Puerto Rico', 'name_lan'=>'ፑኤርቶ ሪኮ','description'=> 'PR','description_lan'=>''],
            ['name' => 'Qatar', 'name_lan'=>'ኳታር','description'=> 'QA','description_lan'=>''],
            ['name' => 'Réunion', 'name_lan'=>'ሬዩኒዮን','description'=> 'RE','description_lan'=>''],
            ['name' => 'Romania', 'name_lan'=>'ሮማኒያ','description'=> 'RO','description_lan'=>''],
            ['name' => 'Russian Federation', 'name_lan'=>'የራሺያ ፌዴሬሽን','description'=> 'RU','description_lan'=>''],
            ['name' => 'Rwanda', 'name_lan'=>'ሩዋንዳ','description'=> 'RW','description_lan'=>''],
            ['name' => 'Saint Barthélemy', 'name_lan'=>'ቅዱስ ባርቴሌሚ','description'=> 'BL','description_lan'=>''],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'name_lan'=>'ሰይንት ሄሌና','description'=> 'SH','description_lan'=>''],
            ['name' => 'Saint Kitts and Nevis', 'name_lan'=>'ሰይንት ኪትስ እና ኔቪስ','description'=> 'KN','description_lan'=>''],
            ['name' => 'Saint Lucia', 'name_lan'=>'ሰይንት ሉካስ','description'=> 'LC','description_lan'=>''],
            ['name' => 'Saint Martin (French part)', 'name_lan'=>'ቅዱስ ማርቲን (የፈረንሳይ ክፍል)','description'=> 'MF','description_lan'=>''],
            ['name' => 'Saint Pierre and Miquelon', 'name_lan'=>'ቅዱስ ፒዬር እና ሚኬሎን','description'=> 'PM','description_lan'=>''],
            ['name' => 'Saint Vincent and the Grenadines', 'name_lan'=>'ሰይንት ቪንሴንት እና ጀሬናዲኔስ','description'=> 'VC','description_lan'=>''],
            ['name' => 'Samoa', 'name_lan'=>'ሳሞአ','description'=> 'WS','description_lan'=>''],
            ['name' => 'San Marino', 'name_lan'=>'ሳን ማሪኖ','description'=> 'SM','description_lan'=>''],
            ['name' => 'Sao Tome and Principe', 'name_lan'=>'ሳኦ ቶሜ እና ፕሪንቺፔ','description'=> 'ST','description_lan'=>''],
            ['name' => 'Saudi Arabia', 'name_lan'=>'ሳውዲ አረብያ','description'=> 'SA','description_lan'=>''],
            ['name' => 'Senegal', 'name_lan'=>'ሴኔጋል','description'=> 'SN','description_lan'=>''],
            ['name' => 'Serbia', 'name_lan'=>'ሴርቢያ','description'=> 'RS','description_lan'=>''],
            ['name' => 'Seychelles', 'name_lan'=>'ሲሼልስ','description'=> 'SC','description_lan'=>''],
            ['name' => 'Sierra Leone', 'name_lan'=>'ሰራሊዮን','description'=> 'SL','description_lan'=>''],
            ['name' => 'Singapore', 'name_lan'=>'ስንጋፖር','description'=> 'SG','description_lan'=>''],
            ['name' => 'Sint Maarten (Dutch part)', 'name_lan'=>'ሲንት ማርተን (የደች ክፍል)','description'=> 'SX','description_lan'=>''],
            ['name' => 'Slovakia', 'name_lan'=>'ስሎቫኒካ','description'=> 'SK','description_lan'=>''],
            ['name' => 'Slovenia', 'name_lan'=>'ስሎቫኒያ','description'=> 'SI','description_lan'=>''],
            ['name' => 'Solomon Islands', 'name_lan'=>'የሰሎሞን አይስላንድስ','description'=> 'SB','description_lan'=>''],
            ['name' => 'Somalia', 'name_lan'=>'ሶማሊያ','description'=> 'SO','description_lan'=>''],
            ['name' => 'South Africa', 'name_lan'=>'ደቡብ አፍሪካ','description'=> 'ZA','description_lan'=>''],
            ['name' => 'South Georgia and the South Sandwich Islands', 'name_lan'=>'ደቡብ ጆርጂያ','description'=> 'GS','description_lan'=>''],
            ['name' => 'South Sudan', 'name_lan'=>'ደቡብ ሱዳን','description'=> 'SS','description_lan'=>''],
            ['name' => 'Spain', 'name_lan'=>'ስፔን','description'=> 'ES','description_lan'=>''],
            ['name' => 'Sri Lanka', 'name_lan'=>'ስሪ ላንካ','description'=> 'LK','description_lan'=>''],
            ['name' => 'Sudan', 'name_lan'=>'ሱዳን','description'=> 'SD','description_lan'=>''],
            ['name' => 'Suriname', 'name_lan'=>'ሱሪናሜ','description'=> 'SR','description_lan'=>''],
            ['name' => 'Svalbard and Jan Mayen', 'name_lan'=>'ስቫልባርድ እና ጃን ማይየን','description'=> 'SJ','description_lan'=>''],
            ['name' => 'Swaziland', 'name_lan'=>'ስዋዝላድ','description'=> 'SZ','description_lan'=>''],
            ['name' => 'Sweden', 'name_lan'=>'ስዊዲን','description'=> 'SE','description_lan'=>''],
            ['name' => 'Switzerland', 'name_lan'=>'ስዊዘሪላንድ','description'=> 'CH','description_lan'=>''],
            ['name' => 'Syrian Arab Republic', 'name_lan'=>'ሶሪያ አረብ ሪፐብሊክ','description'=> 'SY','description_lan'=>''],
            ['name' => 'Taiwan', 'name_lan'=>'ታይዋን','description'=> 'TW','description_lan'=>''],
            ['name' => 'Tajikistan', 'name_lan'=>'ታጂኪስታን','description'=> 'TJ','description_lan'=>''],
            ['name' => 'Tanzania, United Republic of', 'name_lan'=>'ታንዛንኒያ','description'=> 'TZ','description_lan'=>''],
            ['name' => 'Thailand', 'name_lan'=>'ታይላንድ','description'=> 'TH','description_lan'=>''],
            ['name' => 'Timor-Leste', 'name_lan'=>'ቲሞር-ሌስቴ','description'=> 'TL','description_lan'=>''],
            ['name' => 'Togo', 'name_lan'=>'ቲሞር-ሌስቴ','description'=> 'TG','description_lan'=>''],
            ['name' => 'Tokelau', 'name_lan'=>'ቶኬላኡ','description'=> 'TK','description_lan'=>''],
            ['name' => 'Tonga', 'name_lan'=>'ቶንጋ','description'=> 'TO','description_lan'=>''],
            ['name' => 'Trinidad and Tobago', 'name_lan'=>'ትሪኒዳድ እና ቶባጎ','description'=> 'TT','description_lan'=>''],
            ['name' => 'Tunisia', 'name_lan'=>'ቱንሲያ','description'=> 'TN','description_lan'=>''],
            ['name' => 'Turkey', 'name_lan'=>'ቱሪክ','description'=> 'TR','description_lan'=>''],
            ['name' => 'Turkmenistan', 'name_lan'=>'ቱርክሜኒስታን','description'=> 'TM','description_lan'=>''],
            ['name' => 'Turks and Caicos Islands', 'name_lan'=>'የቱርኮች እና የካይኮስ ደሴቶች','description'=> 'TC','description_lan'=>''],
            ['name' => 'Tuvalu', 'name_lan'=>'ቱቫሉ','description'=> 'TV','description_lan'=>''],
            ['name' => 'Uganda', 'name_lan'=>'ኡጋንዳ','description'=> 'UG','description_lan'=>''],
            ['name' => 'Ukraine', 'name_lan'=>'ዩክሬን','description'=> 'UA','description_lan'=>''],
            ['name' => 'United Arab Emirates', 'name_lan'=>'ዩናይቲድ አራብ ኤሚራትስ','description'=> 'AE','description_lan'=>''],
            ['name' => 'United Kingdom', 'name_lan'=>'እንግሊዝ','description'=> 'GB','description_lan'=>''],
            ['name' => 'United States', 'name_lan'=>'ዩናይትድ ስቴተት','description'=> 'US','description_lan'=>''],
            ['name' => 'United States Minor Outlying Islands', 'name_lan'=>'ዩናይትድ ስቴተት','description'=> 'UM','description_lan'=>''],
            ['name' => 'Uruguay', 'name_lan'=>'ኡራጋይ','description'=> 'UY','description_lan'=>''],
            ['name' => 'Uzbekistan', 'name_lan'=>'ኡዝቤክስታን','description'=> 'UZ','description_lan'=>''],
            ['name' => 'Vanuatu', 'name_lan'=>'ቫኑአቱ','description'=> 'VU','description_lan'=>''],
            ['name' => 'Venezuela, Bolivarian Republic of', 'name_lan'=>'ቨንዙዋላ','description'=> 'VE','description_lan'=>''],
            ['name' => 'Viet Nam', 'name_lan'=>'ቪትናም','description'=> 'VN','description_lan'=>''],
            ['name' => 'Virgin Islands, British', 'name_lan'=>'ቨርጂን ደሴቶች','description'=> 'VG','description_lan'=>''],
            ['name' => 'Virgin Islands, U.S.', 'name_lan'=>'ቨርጂን ደሴቶች','description'=> 'VI','description_lan'=>''],
            ['name' => 'Wallis and Futuna', 'name_lan'=>'ዋሊስ እና ፉቱና','description'=> 'WF','description_lan'=>''],
            ['name' => 'Western Sahara', 'name_lan'=>'ምዕራባዊ ሰሃራ','description'=> 'EH','description_lan'=>''],
            ['name' => 'Yemen', 'name_lan'=>'የመን','description'=> 'YE','description_lan'=>''],
            ['name' => 'Zambia', 'name_lan'=>'ዛምቢያ','description'=> 'ZM','description_lan'=>''],
            ['name' => 'Zimbabwe', 'name_lan'=>'ዝምባቡዌ','description'=> 'ZW','description_lan'=>''],
        ];
        DB::beginTransaction();
        foreach ($countries as $country){
            if(Country::where('name', $country['name'])->exists()){
                $country_obj = Country::where('name', $country['name'])->first();
                $country_obj->update($country);
            }
            else{
                Country::create($country);
            }
        }
        DB::commit();
    }
}
