<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DB::table('countries')->truncate();
        $countries = [
            ['name' => 'Afghanistan', 'name_am'=>'አፍጋኒስታን','description'=> 'AF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Åland Islands', 'name_am'=>'የአላንድ ደሴቶች','description'=> 'AX','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Albania', 'name_am'=>'አልባኒያ','description'=> 'AL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Algeria', 'name_am'=>'አልጄሪያ','description'=> 'DZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'American Samoa', 'name_am'=>'አሜሪካዊ ሳሞአ','description'=> 'AS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Andorra', 'name_am'=>'አንዶራ','description'=> 'AD','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Angola', 'name_am'=>'አንጎላ','description'=> 'AO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Anguilla', 'name_am'=>'አንጉላ','description'=> 'AI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Antarctica', 'name_am'=>'አንታርክቲካ','description'=> 'AQ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Antigua and Barbuda', 'name_am'=>'አንቲጉአ እና ባርቡዳ','description'=> 'AG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Argentina', 'name_am'=>'አርጀንቲና','description'=> 'AR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Armenia', 'name_am'=>'አርሜኒያ','description'=> 'AM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Aruba', 'name_am'=>'አሩባ','description'=> 'AW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Australia', 'name_am'=>'አውስትራሊያ','description'=> 'AU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Austria', 'name_am'=>'ኦስትራ','description'=> 'AT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Azerbaijan', 'name_am'=>'አዘርባጃን','description'=> 'AZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bahamas', 'name_am'=>'ባሐማስ','description'=> 'BS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bahrain', 'name_am'=>'ባሃሬን','description'=> 'BH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bangladesh', 'name_am'=>'ባንግላድሽ','description'=> 'BD','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Barbados', 'name_am'=>'ባርባዶስ','description'=> 'BB','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Belarus', 'name_am'=>'ቤላሩስ','description'=> 'BY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Belgium', 'name_am'=>'ቤልጄም','description'=> 'BE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Belize', 'name_am'=>'ቤሊዜ','description'=> 'BZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Benin', 'name_am'=>'ቤኒኒ','description'=> 'BJ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bermuda', 'name_am'=>'ቤርሙዳ','description'=> 'BM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bhutan', 'name_am'=>'በሓቱን','description'=> 'BT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bolivia, Plurinational State of', 'name_am'=>'ቦሊቪያ','description'=> 'BO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'name_am'=>'ቦናይየር','description'=> 'BQ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bosnia and Herzegovina', 'name_am'=>'ቦስኒያ እና ሔርዞጎቪያ','description'=> 'BA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Botswana', 'name_am'=>'ቦትስዋና','description'=> 'BW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bouvet Island', 'name_am'=>'ቡቬት ደሴት','description'=> 'BV','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Brazil', 'name_am'=>'ብራዚል','description'=> 'BR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'British Indian Ocean Territory', 'name_am'=>'የእንግሊዝ የሕንድ ውቅያኖስ ግዛት','description'=> 'IO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Brunei Darussalam', 'name_am'=>'ብሩኒ ዳሩሰላም','description'=> 'BN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Bulgaria', 'name_am'=>'ቡልጋሪያ','description'=> 'BG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Burkina Faso', 'name_am'=>' ቡርክናፋሶ','description'=> 'BF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Burundi', 'name_am'=>'ቡሩንዲ','description'=> 'BI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cambodia', 'name_am'=>'ካምቦዲያ','description'=> 'KH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cameroon', 'name_am'=>'ካሜሩን','description'=> 'CM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Canada', 'name_am'=>'ካናዳ','description'=> 'CA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cape Verde', 'name_am'=>'ኬፕ ቬሪዴ','description'=> 'CV','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cayman Islands', 'name_am'=>'ኬይማን አይስላንድ','description'=> 'KY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Central African Republic', 'name_am'=>'','description'=> 'CF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Chad', 'name_am'=>'ሴንትራል አፍሪካ ሪፑቢሊክ','description'=> 'TD','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Chile', 'name_am'=>' ቻድ','description'=> 'CL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'China', 'name_am'=>'ቺሊ','description'=> 'CN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Christmas Island', 'name_am'=>' ቻይና','description'=> 'CX','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cocos (Keeling) Islands', 'name_am'=>' የገና ደሴት','description'=> 'CC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Colombia', 'name_am'=>'ኮኮስ (ኬሊንግ) ደሴቶች','description'=> 'CO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Comoros', 'name_am'=>'ኮሎምቢያ','description'=> 'KM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Congo', 'name_am'=>'ኮሞሮስ','description'=> 'CG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Congo, the Democratic Republic of the', 'name_am'=>'ኮንጎ','description'=> 'CD','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cook Islands', 'name_am'=>'ኩክ አይስላንድስ','description'=> 'CK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Costa Rica', 'name_am'=>'ኮስታሪካ','description'=> 'CR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Côte d\'Ivoire', 'name_am'=>'ኮትዲቫር','description'=> 'CI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Croatia', 'name_am'=>'ክሮሽያ','description'=> 'HR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cuba', 'name_am'=>'ኩባ','description'=> 'CU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Curaçao', 'name_am'=>'ኩራኦ','description'=> 'CW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Cyprus', 'name_am'=>'ቆጵሮስ','description'=> 'CY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Czech Republic', 'name_am'=>'ቼክ ሪፐብሊክ','description'=> 'CZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Denmark', 'name_am'=>'ዴንማሪክ','description'=> 'DK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Djibouti', 'name_am'=>'ጅቡቲ','description'=> 'DJ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Dominica', 'name_am'=>'ዶሚኒካ','description'=> 'DM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Dominican Republic', 'name_am'=>'ዶሚኒካን ሪፑብሊክ','description'=> 'DO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Ecuador', 'name_am'=>'ኢኳዶር','description'=> 'EC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Egypt', 'name_am'=>'ግብጽ','description'=> 'EG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'El Salvador', 'name_am'=>'ኤልሳልቫዶር','description'=> 'SV','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Equatorial Guinea', 'name_am'=>'ኢኳቶሪያል ጊኒ','description'=> 'GQ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Eritrea', 'name_am'=>'ኤርትሪያ','description'=> 'ER','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Estonia', 'name_am'=>'ኢስቶኒያ','description'=> 'EE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Ethiopia', 'name_am'=>'ኢትዮጵያ','description'=> 'ET','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Falkland Islands (Malvinas)', 'name_am'=>'የፎክላንድ ደሴቶች (ማልቪናስ)','description'=> 'FK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Faroe Islands', 'name_am'=>'ፋሮ ደሴቶች','description'=> 'FO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Fiji', 'name_am'=>'ፊጂ','description'=> 'FJ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Finland', 'name_am'=>'ፊኒላንድ','description'=> 'FI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'France', 'name_am'=>'ፈረንሳይ','description'=> 'FR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'French Guiana', 'name_am'=>'የፈረንሳይ ጉያና','description'=> 'GF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'French Polynesia', 'name_am'=>'የፈረንሳይ ፖሊኔዥያ','description'=> 'PF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'French Southern Territories', 'name_am'=>'የፈረንሳይ ደቡባዊ ግዛቶች','description'=> 'TF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Gabon', 'name_am'=>'ጋቦን','description'=> 'GA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Gambia', 'name_am'=>'ጋምቢያ','description'=> 'GM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Georgia', 'name_am'=>'ጆርጂያ','description'=> 'GE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Germany', 'name_am'=>'ጀርመን','description'=> 'DE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Ghana', 'name_am'=>'ጋና','description'=> 'GH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Gibraltar', 'name_am'=>'ጊብራልታር','description'=> 'GI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Greece', 'name_am'=>'ግሪክ','description'=> 'GR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Greenland', 'name_am'=>'ግሪንላንድ','description'=> 'GL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Grenada', 'name_am'=>'ግሪንዳዳ','description'=> 'GD','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Guadeloupe', 'name_am'=>'ጓደሎፕ','description'=> 'GP','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Guam', 'name_am'=>'ጉአሜ','description'=> 'GU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Guatemala', 'name_am'=>'ጓቴማላ','description'=> 'GT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Guernsey', 'name_am'=>'ገርንሴይ','description'=> 'GG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Guinea', 'name_am'=>'ጊኒ','description'=> 'GN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Guinea-Bissau', 'name_am'=>'ጊኒ ቢሳው','description'=> 'GW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Guyana', 'name_am'=>'ጉያና','description'=> 'GY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Haiti', 'name_am'=>'ሓይቲ','description'=> 'HT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'name_am'=>'ሄርድ ደሴት እና ማክዶናልድ ማክዶናልድ ደሴቶች','description'=> 'HM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Holy See (Vatican City State)', 'name_am'=>'ቅድስት መንበር (የቫቲካን ከተማ ግዛት)','description'=> 'VA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Honduras', 'name_am'=>'ሆንዱራስ','description'=> 'HN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Hong Kong', 'name_am'=>'ሆንግ ኮንግ','description'=> 'HK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Hungary', 'name_am'=>'ሃንጋሪ','description'=> 'HU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Iceland', 'name_am'=>'አይስላንድ','description'=> 'IS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'India', 'name_am'=>'ሕንድ','description'=> 'IN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Indonesia', 'name_am'=>'ኢንዶኔዥያ','description'=> 'ID','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Iran, Islamic Republic of', 'name_am'=>'ኢራን','description'=> 'IR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Iraq', 'name_am'=>'ኢራቅ','description'=> 'IQ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Ireland', 'name_am'=>'አይርላድ','description'=> 'IE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Isle of Man', 'name_am'=>'የሰው ደሴት','description'=> 'IM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Israel', 'name_am'=>'እስራኤል','description'=> 'IL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Italy', 'name_am'=>'ጣሊያን','description'=> 'IT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Jamaica', 'name_am'=>'ጃማይካ','description'=> 'JM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Japan', 'name_am'=>'ጃፓን','description'=> 'JP','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Jersey', 'name_am'=>'ጀርሲ','description'=> 'JE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Jordan', 'name_am'=>'ዮርዳኖስ','description'=> 'JO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Kazakhstan', 'name_am'=>'ካዛክስታን','description'=> 'KZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Kenya', 'name_am'=>'ኬንያ','description'=> 'KE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Kiribati', 'name_am'=>'ኪሪባቲ','description'=> 'KI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Korea, Democratic People\'s Republic of', 'name_am'=>'ኮሪያ','description'=> 'KP','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Korea, Republic of', 'name_am'=>'ኮሪያ','description'=> 'KR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Kuwait', 'name_am'=>'ኵዌት','description'=> 'KW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Kyrgyzstan', 'name_am'=>'ክይርጋዝስታን','description'=> 'KG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Lao People\'s Democratic Republic', 'name_am'=>'ላኦ ሕዝባዊ ዴሞክራሲያዊ ሪፐብሊክ','description'=> 'LA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Latvia', 'name_am'=>'ላቲቪያ','description'=> 'LV','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Lebanon', 'name_am'=>'ሊባኖስ','description'=> 'LB','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Lesotho', 'name_am'=>'ሌስቶ','description'=> 'LS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Liberia', 'name_am'=>'ላይቤሪያ','description'=> 'LR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Libya', 'name_am'=>'ሊቢያ','description'=> 'LY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Liechtenstein', 'name_am'=>'ለይችቴንስቴይን','description'=> 'LI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Lithuania', 'name_am'=>'ሊቱአኒያ','description'=> 'LT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Luxembourg', 'name_am'=>'ሉዘምቤርግ','description'=> 'LU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Macao', 'name_am'=>'ማካው','description'=> 'MO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'name_am'=>'መቄዶኒያ','description'=> 'MK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Madagascar', 'name_am'=>'ማዳጋስካር','description'=> 'MG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Malawi', 'name_am'=>'ማላዊ','description'=> 'MW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Malaysia', 'name_am'=>'ማሌዥያ','description'=> 'MY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Maldives', 'name_am'=>'ማልዲቬስ','description'=> 'MV','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Mali', 'name_am'=>'ማሊ','description'=> 'ML','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Malta', 'name_am'=>'ማልታ','description'=> 'MT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Marshall Islands', 'name_am'=>'ማርሻል አይስላንድ','description'=> 'MH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Martinique', 'name_am'=>'ማርቲኒክ','description'=> 'MQ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Mauritania', 'name_am'=>'ሞሪታኒያ','description'=> 'MR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Mauritius', 'name_am'=>'ሞሪሼስ','description'=> 'MU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Mayotte', 'name_am'=>'ማዮት','description'=> 'YT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Mexico', 'name_am'=>'ሜክስኮ','description'=> 'MX','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Micronesia, Federated States of', 'name_am'=>'ሚክሮኔዥያ','description'=> 'FM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Moldova, Republic of', 'name_am'=>'ሞልዶቫ','description'=> 'MD','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Monaco', 'name_am'=>'ሞናኮ','description'=> 'MC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Mongolia', 'name_am'=>'ሞንጎሊያ','description'=> 'MN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Montenegro', 'name_am'=>'ሞንቴኔግሮ','description'=> 'ME','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Montserrat', 'name_am'=>'ሞንትሴራት','description'=> 'MS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Morocco', 'name_am'=>'ሞሮኮ','description'=> 'MA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Mozambique', 'name_am'=>'ሞዛምቢክ','description'=> 'MZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Myanmar', 'name_am'=>'ማይንማር','description'=> 'MM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Namibia', 'name_am'=>'ናምቢያ','description'=> 'NA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Nauru', 'name_am'=>'ናኡሩ','description'=> 'NR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Nepal', 'name_am'=>'ኔፓል','description'=> 'NP','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Netherlands', 'name_am'=>'ኔዜሪላንድ','description'=> 'NL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'New Caledonia', 'name_am'=>'ኒው ካሌዶኒያ','description'=> 'NC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'New Zealand', 'name_am'=>'ኒውዚላንድ','description'=> 'NZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Nicaragua', 'name_am'=>'ኒካራጉአ','description'=> 'NI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Niger', 'name_am'=>'ኒጀር','description'=> 'NE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Nigeria', 'name_am'=>'ናይጄሪያ','description'=> 'NG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Niue', 'name_am'=>'ኒይኡ','description'=> 'NU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Norfolk Island', 'name_am'=>'ኖርፎልክ አይስላንድስ','description'=> 'NF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Northern Mariana Islands', 'name_am'=>'የሰሜናዊ ማሪያና አይስላንድስ','description'=> 'MP','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Norway', 'name_am'=>'ኖርዌይ','description'=> 'NO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Oman', 'name_am'=>'ኦማን','description'=> 'OM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Pakistan', 'name_am'=>'ፓኪስታን','description'=> 'PK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Palau', 'name_am'=>'ፓላኡ','description'=> 'PW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Palestine, State of', 'name_am'=>'ፍልስጥኤም','description'=> 'PS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Panama', 'name_am'=>'ፓናማ','description'=> 'PA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Papua New Guinea', 'name_am'=>'ፓፓያ ኒው ጊኒ','description'=> 'PG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Paraguay', 'name_am'=>'ፓራጓይ','description'=> 'PY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Peru', 'name_am'=>'ፔሩ','description'=> 'PE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Philippines', 'name_am'=>'ፊሊፕንሲ','description'=> 'PH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Pitcairn', 'name_am'=>'ፒትካርን','description'=> 'PN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Poland', 'name_am'=>'ፖላንድ','description'=> 'PL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Portugal', 'name_am'=>'ፖርቹጋል','description'=> 'PT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Puerto Rico', 'name_am'=>'ፑኤርቶ ሪኮ','description'=> 'PR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Qatar', 'name_am'=>'ኳታር','description'=> 'QA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Réunion', 'name_am'=>'ሬዩኒዮን','description'=> 'RE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Romania', 'name_am'=>'ሮማኒያ','description'=> 'RO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Russian Federation', 'name_am'=>'የራሺያ ፌዴሬሽን','description'=> 'RU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Rwanda', 'name_am'=>'ሩዋንዳ','description'=> 'RW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saint Barthélemy', 'name_am'=>'ቅዱስ ባርቴሌሚ','description'=> 'BL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'name_am'=>'ሰይንት ሄሌና','description'=> 'SH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saint Kitts and Nevis', 'name_am'=>'ሰይንት ኪትስ እና ኔቪስ','description'=> 'KN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saint Lucia', 'name_am'=>'ሰይንት ሉካስ','description'=> 'LC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saint Martin (French part)', 'name_am'=>'ቅዱስ ማርቲን (የፈረንሳይ ክፍል)','description'=> 'MF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saint Pierre and Miquelon', 'name_am'=>'ቅዱስ ፒዬር እና ሚኬሎን','description'=> 'PM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saint Vincent and the Grenadines', 'name_am'=>'ሰይንት ቪንሴንት እና ጀሬናዲኔስ','description'=> 'VC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Samoa', 'name_am'=>'ሳሞአ','description'=> 'WS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'San Marino', 'name_am'=>'ሳን ማሪኖ','description'=> 'SM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Sao Tome and Principe', 'name_am'=>'ሳኦ ቶሜ እና ፕሪንቺፔ','description'=> 'ST','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Saudi Arabia', 'name_am'=>'ሳውዲ አረብያ','description'=> 'SA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Senegal', 'name_am'=>'ሴኔጋል','description'=> 'SN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Serbia', 'name_am'=>'ሴርቢያ','description'=> 'RS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Seychelles', 'name_am'=>'ሲሼልስ','description'=> 'SC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Sierra Leone', 'name_am'=>'ሰራሊዮን','description'=> 'SL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Singapore', 'name_am'=>'ስንጋፖር','description'=> 'SG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Sint Maarten (Dutch part)', 'name_am'=>'ሲንት ማርተን (የደች ክፍል)','description'=> 'SX','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Slovakia', 'name_am'=>'ስሎቫኒካ','description'=> 'SK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Slovenia', 'name_am'=>'ስሎቫኒያ','description'=> 'SI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Solomon Islands', 'name_am'=>'የሰሎሞን አይስላንድስ','description'=> 'SB','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Somalia', 'name_am'=>'ሶማሊያ','description'=> 'SO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'South Africa', 'name_am'=>'ደቡብ አፍሪካ','description'=> 'ZA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'South Georgia and the South Sandwich Islands', 'name_am'=>'ደቡብ ጆርጂያ','description'=> 'GS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'South Sudan', 'name_am'=>'ደቡብ ሱዳን','description'=> 'SS','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Spain', 'name_am'=>'ስፔን','description'=> 'ES','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Sri Lanka', 'name_am'=>'ስሪ ላንካ','description'=> 'LK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Sudan', 'name_am'=>'ሱዳን','description'=> 'SD','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Suriname', 'name_am'=>'ሱሪናሜ','description'=> 'SR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Svalbard and Jan Mayen', 'name_am'=>'ስቫልባርድ እና ጃን ማይየን','description'=> 'SJ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Swaziland', 'name_am'=>'ስዋዝላድ','description'=> 'SZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Sweden', 'name_am'=>'ስዊዲን','description'=> 'SE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Switzerland', 'name_am'=>'ስዊዘሪላንድ','description'=> 'CH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Syrian Arab Republic', 'name_am'=>'ሶሪያ አረብ ሪፐብሊክ','description'=> 'SY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Taiwan', 'name_am'=>'ታይዋን','description'=> 'TW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Tajikistan', 'name_am'=>'ታጂኪስታን','description'=> 'TJ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Tanzania, United Republic of', 'name_am'=>'ታንዛንኒያ','description'=> 'TZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Thailand', 'name_am'=>'ታይላንድ','description'=> 'TH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Timor-Leste', 'name_am'=>'ቲሞር-ሌስቴ','description'=> 'TL','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Togo', 'name_am'=>'ቲሞር-ሌስቴ','description'=> 'TG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Tokelau', 'name_am'=>'ቶኬላኡ','description'=> 'TK','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Tonga', 'name_am'=>'ቶንጋ','description'=> 'TO','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Trinidad and Tobago', 'name_am'=>'ትሪኒዳድ እና ቶባጎ','description'=> 'TT','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Tunisia', 'name_am'=>'ቱንሲያ','description'=> 'TN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Turkey', 'name_am'=>'ቱሪክ','description'=> 'TR','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Turkmenistan', 'name_am'=>'ቱርክሜኒስታን','description'=> 'TM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Turks and Caicos Islands', 'name_am'=>'የቱርኮች እና የካይኮስ ደሴቶች','description'=> 'TC','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Tuvalu', 'name_am'=>'ቱቫሉ','description'=> 'TV','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Uganda', 'name_am'=>'ኡጋንዳ','description'=> 'UG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Ukraine', 'name_am'=>'ዩክሬን','description'=> 'UA','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'United Arab Emirates', 'name_am'=>'ዩናይቲድ አራብ ኤሚራትስ','description'=> 'AE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'United Kingdom', 'name_am'=>'እንግሊዝ','description'=> 'GB','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'United States', 'name_am'=>'ዩናይትድ ስቴተት','description'=> 'US','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'United States Minor Outlying Islands', 'name_am'=>'ዩናይትድ ስቴተት','description'=> 'UM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Uruguay', 'name_am'=>'ኡራጋይ','description'=> 'UY','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Uzbekistan', 'name_am'=>'ኡዝቤክስታን','description'=> 'UZ','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Vanuatu', 'name_am'=>'ቫኑአቱ','description'=> 'VU','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Venezuela, Bolivarian Republic of', 'name_am'=>'ቨንዙዋላ','description'=> 'VE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Viet Nam', 'name_am'=>'ቪትናም','description'=> 'VN','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Virgin Islands, British', 'name_am'=>'ቨርጂን ደሴቶች','description'=> 'VG','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Virgin Islands, U.S.', 'name_am'=>'ቨርጂን ደሴቶች','description'=> 'VI','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Wallis and Futuna', 'name_am'=>'ዋሊስ እና ፉቱና','description'=> 'WF','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Western Sahara', 'name_am'=>'ምዕራባዊ ሰሃራ','description'=> 'EH','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Yemen', 'name_am'=>'የመን','description'=> 'YE','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Zambia', 'name_am'=>'ዛምቢያ','description'=> 'ZM','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
            ['name' => 'Zimbabwe', 'name_am'=>'ዝምባቡዌ','description'=> 'ZW','description_am'=>'','name_fr'=>'','description_fr'=>'','name_it'=>'','description_it'=>''],
        ];
        DB::beginTransaction();
        foreach ($countries as $country){
            if(Country::where('name', $country['name'])->exists()){
                $country_obj = Country::where('name', $country['name'])->first();
                $country_obj->update($country);
            }
            else{
                Country::create($country);
            }
        }
        DB::commit();
    }
}
